### ISSUE TITLE
Current-build not available under releases, resulting in setup-watcom failures

### ISSUE THREAD

**Issue by sezero** [open-watcom/open-watcom-v2#1222]
As the title says. The github actions workflows using setup-watcom fail because of it:

```
Downloading https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.xz.
  Downloading failed.
Downloading https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.gz.
  Error: Unexpected HTTP response: 404
```

**Comment by jmalak** [comment]
Thanks for bug report.
it is strange, old version should be replaced by new one after successful build that old version should be always available. It doesn't happen.

**Comment by jmalak** [comment]
I manually start build ones more to create missing build.
Anyway it is strange, because code which handle build was not change for long time.
Last build don't reported any problem that it looks like some mistake in script handling build.

**Comment by sezero** [comment]
Seems like Current-build is back for the moment. Maybe was a one-off?

Feel free to close when ready

**Comment by jmalak** [comment]
I get full log from last build that I will analyse what could happen.
I will monitor the build process for a few days if it happen again.

**Comment by jmalak** [comment]
Today it happend after run "Delete Old (Workflow Runs)" process.
It looks like the "Delete Old (Workflow Runs)" process delete CI and Current build for some reason or under some conditions.
I disabled it for now and will do analysis of this process.

**Comment by jmalak** [comment]
It looks like issue with CURL and GitHub REST API.
The problem is that now request for creation of build tag get response 
```
{
"message": "Problems parsing JSON",
"documentation_url": "https://docs.github.com/rest/git/tags#create-a-tag-object"
}
```

It looks like problem with curl option -d.

**Comment by jmalak** [comment]
I hope I fixed issue.
It looks like behaviour of curl tools in powershell somehow changed in GitHub VM image.
As result build scripts were not able create appropriate git build tag.
It looks like remove of powershell curl alias fix the problem.

**Comment by sezero** [comment]
We are now getting the following failure in setup-watcom:

```
Run open-watcom/setup-watcom@v0
  with:
    version: 2.0
Initializing action.
  Error: Input does not meet YAML 1.2 "Core Schema" specification: environment
  Support boolean input list: `true | True | TRUE | false | False | FALSE`
```

**Comment by jmalak** [comment]
It is caused by buggy old version of setup-watcom.
I recompiled it that now it should work again.

**Comment by sezero** [comment]
> It is caused by buggy old version of setup-watcom. I recompiled it that now it should work again.

> We are now getting the following failure in setup-watcom:
> 
> ```
> Run open-watcom/setup-watcom@v0
>   with:
>     version: 2.0
> Initializing action.
>   Error: Input does not meet YAML 1.2 "Core Schema" specification: environment
>   Support boolean input list: `true | True | TRUE | false | False | FALSE`
> ```

Unfortunately no: I re-tried the workflow and the issue is still there.

If it matters, this is our workflow:

```
name: Build (OpenWatcom)

on: [push, pull_request]

jobs:
  os2:
    name: ${{ matrix.platform.name }}
    runs-on: windows-latest

    strategy:
      matrix:
        platform:
        - { name: Windows, makefile: Makefile.w32 }
        - { name: OS/2,    makefile: Makefile.os2 }

    steps:
      - uses: actions/checkout@v3
      - uses: open-watcom/setup-watcom@v0
      - name: Build SDL2
        run: |
          wmake -f ${{ matrix.platform.makefile }} ENABLE_WERROR=1
      - name: Build tests
        run: |
          cd test && wmake -f ${{ matrix.platform.makefile }} ENABLE_WERROR=1
          cd ..
      - name: Run tests
        if: "matrix.platform.makefile == 'Makefile.w32'"
        run: |
          cd test && wmake -f ${{ matrix.platform.makefile }} check-quick
          cd ..
      - name: distclean
        run: |
          wmake -f ${{ matrix.platform.makefile }} distclean
          cd test && wmake -f ${{ matrix.platform.makefile }} distclean
          cd ..
```
