### ISSUE TITLE
WLink seems to ignore .stack size - always 1000h

### ISSUE THREAD

**Issue by LowLevelMahn** [open-watcom/open-watcom-v2#846]
```
.model small
.stack 1deh <--- 

cseg segment 'CODE'   
  assume cs:cseg
start:        
  mov ax,4c00h
  int 21h
cseg ends

end start
```

wasm exe.asm
wlink.exe name exe.exe system dos file exe.obj
or
wlink.exe name exe.exe format dos file exe.obj

IDA Pro is telling me that the file is maybe packed due to data behind image and IDA detects a stacksize of 1000h
radare2-5.6.6-w64\bin\rabin2.exe -H exe.exe does not show the exe header (that is clearly a bug in radare2 - it should at least show the header, but also something that only happens when using wlink)

my own exe header tool is telling me:

```
exe_header:
  signature: MZ
  bytes_in_last_block: 0x0025
  blocks_in_file: 0x0001
  num_relocs: 0x0000
  header_paragraphs: 0x0002
  min_extra_paragraphs: 0x0101
  max_extra_paragraphs: 0xffff
  ss:sp: 0x0001:0x1000 <--- stacksize 1000h
  checksum: 0x0000
  cs:ip: 0x0000:0x0000
  reloc_table_offset: 0x0020
  overlay_number: 0x0000

```

linking with ulink, optlink, tlink giving me the correct stack size in the exe header
IDA Pro does not say the file is maybe packed and i see the correct stacksize in disassembly
and radare2-5.6.6-w64\bin\rabin2.exe -H exe.exe shows

```
ii 69 64
[0000:0000]  Signature           MZ
[0000:0002]  BytesInLastBlock    0x0045
[0000:0004]  BlocksInFile        0x0001
[0000:0006]  NumRelocs           0x0000
[0000:0008]  HeaderParagraphs    0x0004
[0000:000a]  MinExtraParagraphs  0x001f
[0000:000c]  MaxExtraParagraphs  0xffff
[0000:000e]  InitialSs           0x0001
[0000:0010]  InitialSp           0x01de <--------- the corrent size from .stack directive
[0000:0012]  Checksum            0x0000
[0000:0014]  InitialIp           0x0000
[0000:0016]  InitialCs           0x0000
[0000:0018]  RelocTableOffset    0x0040
[0000:001a]  OverlayNumber       0x0000

```

does wlink ignore my given stack size intentional?
